name: deploy-api
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "stage|prod"
        required: true
        default: "stage"
  push:
    tags: ['release-*']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          flyctl deploy --app $FLY_APP_NAME --remote-only --strategy rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME:  ${{ secrets.FLY_APP_NAME }}
