name: deploy-api
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "stage|prod"
        required: true
        default: "stage"
  push:
    tags: ['release-*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # avoid git 128 issues

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      # IMPORTANT: run from apps/api so flyctl sees fly.toml & Dockerfile
      - name: Deploy to Fly.io (apps/api)
        working-directory: apps/api
        run: |
          flyctl deploy --remote-only --strategy rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # FLY_APP_NAME is read from fly.toml; not strictly required here
