name: deploy-api
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "stage|prod"
        required: true
        default: "stage"
  push:
    tags: ['release-*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure full git context (avoids git errors)

      # Mark the workspace as safe for git (prevents exit code 128)
      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io (apps/api)
        run: |
          flyctl deploy \
            --config apps/api/fly.toml \
            --dockerfile apps/api/Dockerfile \
            --path apps/api \
            --remote-only \
            --strategy rolling
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME:  ${{ secrets.FLY_APP_NAME }}
