name: sbom
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SBOM (web - npm)
        uses: anchore/sbom-action@v0
        with:
          path: ./apps/web
          format: cyclonedx-json
          artifact-name: sbom-web.json

      - name: SBOM (api - python)
        uses: anchore/sbom-action@v0
        with:
          path: ./apps/api
          format: cyclonedx-json
          artifact-name: sbom-api.json
